import:
  - ~/.config/alacritty/themes/Rose-pine.yml


env:
  TERM: xterm-256color

window:
  dimensions:
    columns: 120
    lines: 30

  padding:
    x: 3
    y: 3

  decorations: full

  opacity: 0.9

font:
############### JetBrains ################
  normal:
    family: JetBrainsMono Nerd Font
    style: Medium

  bold:
    family: JetBrainsMono Nerd Font
    style: Bold

  italic:
    family: JetBrainsMono Nerd Font
    style: Italic

############### Cascadia Code ############
#  normal:
#    family: CaskaydiaCove Nerd Font Mono
#    style: Regular
#  
#  bold:
#    family: CaskaydiaCove Nerd Font Mono
#    style: Bold
#  
#  italic:
#    family: CaskaydiaCove Nerd Font Mono
#    style: Italic

######################################
  size: 9

colors:
  background_opacity: 0.9

cursor:
  # Cursor style
  #
  # Values for `style`:
  #   - ▇ Block
  #   - _ Underline
  #   - | Beam
  style: Beam
